"""initial_schema

Revision ID: 4250e437ab00
Revises: 
Create Date: 2026-03-20 12:08:31.670736
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4250e437ab00'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('consent_status', sa.String(length=20), nullable=True),
    sa.Column('consent_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trait_summary', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('customer_id', name=op.f('pk_customer'))
    )
    op.create_table('store',
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('store_name', sa.String(length=100), nullable=False),
    sa.Column('area', sa.String(length=50), nullable=False),
    sa.Column('format_type', sa.String(length=30), nullable=False),
    sa.Column('open_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('store_id', name=op.f('pk_store'))
    )
    op.create_table('trust_score_snapshot',
    sa.Column('snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('product_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('service_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('proposal_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('operation_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('story_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('overall_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('event_count', sa.Integer(), nullable=True),
    sa.Column('is_reliable', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('snapshot_id', name=op.f('pk_trust_score_snapshot')),
    sa.UniqueConstraint('target_type', 'target_id', 'snapshot_date', name='uq_trust_score_snapshot')
    )
    op.create_table('complaint_inquiry',
    sa.Column('complaint_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('response_time_hours', sa.Integer(), nullable=True),
    sa.Column('resolution_status', sa.String(length=30), nullable=True),
    sa.Column('trust_dimension', sa.String(length=20), nullable=True),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], name=op.f('fk_complaint_inquiry_customer_id_customer')),
    sa.ForeignKeyConstraint(['store_id'], ['store.store_id'], name=op.f('fk_complaint_inquiry_store_id_store')),
    sa.PrimaryKeyConstraint('complaint_id', name=op.f('pk_complaint_inquiry'))
    )
    op.create_table('review_external',
    sa.Column('review_id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=True),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['store.store_id'], name=op.f('fk_review_external_store_id_store')),
    sa.PrimaryKeyConstraint('review_id', name=op.f('pk_review_external'))
    )
    op.create_table('staff',
    sa.Column('staff_id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('staff_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['store.store_id'], name=op.f('fk_staff_store_id_store')),
    sa.PrimaryKeyConstraint('staff_id', name=op.f('pk_staff'))
    )
    op.create_table('trust_event',
    sa.Column('trust_event_id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('trust_dimension', sa.String(length=20), nullable=False),
    sa.Column('sentiment', sa.String(length=10), nullable=False),
    sa.Column('severity', sa.SmallInteger(), nullable=True),
    sa.Column('theme_tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('generated_summary', sa.Text(), nullable=True),
    sa.Column('interpretation', sa.Text(), nullable=True),
    sa.Column('trait_signal', sa.Text(), nullable=True),
    sa.Column('state_signal', sa.Text(), nullable=True),
    sa.Column('meta_signal', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('reviewed_flag', sa.Boolean(), nullable=False),
    sa.Column('generated_by', sa.String(length=20), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('severity >= 1 AND severity <= 3', name=op.f('ck_trust_event_severity_range')),
    sa.ForeignKeyConstraint(['store_id'], ['store.store_id'], name=op.f('fk_trust_event_store_id_store')),
    sa.PrimaryKeyConstraint('trust_event_id', name=op.f('pk_trust_event'))
    )
    op.create_index('idx_trust_event_store_dim_date', 'trust_event', ['store_id', 'trust_dimension', 'detected_at'], unique=False)
    op.create_table('visit',
    sa.Column('visit_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('staff_id', sa.Uuid(), nullable=True),
    sa.Column('visit_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('visit_purpose', sa.String(length=30), nullable=True),
    sa.Column('purchase_flag', sa.Boolean(), nullable=False),
    sa.Column('contact_result', sa.String(length=30), nullable=True),
    sa.Column('out_of_stock_flag', sa.Boolean(), nullable=False),
    sa.Column('alternative_proposed', sa.Boolean(), nullable=True),
    sa.Column('backorder_offered', sa.Boolean(), nullable=True),
    sa.Column('anxiety_tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('next_visit_likelihood', sa.String(length=10), nullable=True),
    sa.Column('staff_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], name=op.f('fk_visit_customer_id_customer')),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.staff_id'], name=op.f('fk_visit_staff_id_staff')),
    sa.ForeignKeyConstraint(['store_id'], ['store.store_id'], name=op.f('fk_visit_store_id_store')),
    sa.PrimaryKeyConstraint('visit_id', name=op.f('pk_visit'))
    )
    op.create_table('feedback',
    sa.Column('feedback_id', sa.Uuid(), nullable=False),
    sa.Column('visit_id', sa.Uuid(), nullable=False),
    sa.Column('score_consultation', sa.SmallInteger(), nullable=False),
    sa.Column('score_information', sa.SmallInteger(), nullable=False),
    sa.Column('score_revisit', sa.SmallInteger(), nullable=False),
    sa.Column('free_comment', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('score_consultation >= 1 AND score_consultation <= 5', name=op.f('ck_feedback_score_consultation_range')),
    sa.CheckConstraint('score_information >= 1 AND score_information <= 5', name=op.f('ck_feedback_score_information_range')),
    sa.CheckConstraint('score_revisit >= 1 AND score_revisit <= 5', name=op.f('ck_feedback_score_revisit_range')),
    sa.ForeignKeyConstraint(['visit_id'], ['visit.visit_id'], name=op.f('fk_feedback_visit_id_visit')),
    sa.PrimaryKeyConstraint('feedback_id', name=op.f('pk_feedback')),
    sa.UniqueConstraint('visit_id', name=op.f('uq_feedback_visit_id'))
    )
    op.create_table('purchase',
    sa.Column('purchase_id', sa.Uuid(), nullable=False),
    sa.Column('visit_id', sa.Uuid(), nullable=False),
    sa.Column('product_category', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('purchased_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('return_flag', sa.Boolean(), nullable=False),
    sa.Column('return_reason_category', sa.String(length=50), nullable=True),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['visit_id'], ['visit.visit_id'], name=op.f('fk_purchase_visit_id_visit')),
    sa.PrimaryKeyConstraint('purchase_id', name=op.f('pk_purchase'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchase')
    op.drop_table('feedback')
    op.drop_table('visit')
    op.drop_index('idx_trust_event_store_dim_date', table_name='trust_event')
    op.drop_table('trust_event')
    op.drop_table('staff')
    op.drop_table('review_external')
    op.drop_table('complaint_inquiry')
    op.drop_table('trust_score_snapshot')
    op.drop_table('store')
    op.drop_table('customer')
    # ### end Alembic commands ###
